docs/index.rst
Beets current has a [wiki page](https://github.com/beetbox/beets/wiki/MediaFile) for MediaFile. Once the move is complete we should remove that page. Here I'm transferring what seemed relevant from there into the docs for MediaFile. Some parts of the wiki page were outdated so I left them out. Ther might be more that I missed.
=> Update docs using beets wiki page

MANIFEST.in
Without these files tests can't be run directly from the unpacked sdist tarball. Closes #13.
=> Include test/__init__.py and test/rsrc in sdist

mediafile.py, test/test_mediafile.py
Save the value in R128_{TRACK,ALBUM}_GAIN tags not as a decimal float but as a
Q7.8 number as demanded by IETF RFC 7845, 5.3.1.
This implementation actually saves a Q8 number, i.e. does not check if the
integer part fits into 7 bits. While reading this is clearly the most sensible
approach. We could consider adding a check when writing and issuing either a
Warning or an Error.
See also [beets #3311](https://github.com/beetbox/beets/issues/3311).
=> format R128 GAIN tags as Q7.8 number

setup.py, test/test_mediafile.py
Mutagen used to not provide this information, now it does, so let's bump the dependency and check for it.
Closes #24 and addresses #23.
=> Check for real bitdepth value in AIFFTest.

docs/index.rst, mediafile.py
According to [the Picard tag mappings documentation](https://picard.musicbrainz.org/docs/mappings/), the "Release Status" tag is mapped to `MUSICBRAINZ_ALBUMSTATUS` for APEv2 and `RELEASESTATUS` for Vorbis comments and the "Release Type" tag is mapped to `MUSICBRAINZ_ALBUMTYPE` for APEv2 and `RELEASETYPE` for Vorbis comments.
Currently, mediafile only reads and writes `MUSICBRAINZ_ALBUMSTATUS` in `albumstatus` for Vorbis comments and APEv2, so it doesn't pick up the value in FLAC files edited with Picard.
Same thing for `albumtype`, `RELEASETYPE` should be supported alongside `MUSICBRAINZ_ALBUMTYPE`.
=> Add RELEASETYPE mapping for albumtype and RELEASESTATUS mapping for albumstatus

mediafile.py, test/test_mediafile_edge.py
`mediafile._sc_encode` had a issue that the value of SoundCheck gain going to 0 when the input gain is extremely large.
I've added a minimum to prevent this problem, so please check it out.
=> Define the minimum value of SoundCheck gain.

docs/index.rst, mediafile.py
Fixes https://github.com/beetbox/mediafile/issues/38
I _think_ this captures the actual behavior, but please correct me if I'm wrong.
=> Fix docs to reflect None return if tag does not exist.

docs/index.rst
For new users (like me) code examples can be very helpful in understanding a library. I added two somewhat specific examples for tasks that I needed for a project to the documentation. I pieced these together by sifting through the unit tests, so I am not sure if it is the best way to go about it. 
If you are interested I could expand this pull request a bit by adding more examples and maybe some text.
=> Add code examples to documentation

docs/index.rst, mediafile.py, test/test_mediafile.py
Also adds additional barcode tags to read from
Sources for tag mapping:
https://picard-docs.musicbrainz.org/en/appendices/tag_mapping.html#artists
https://wiki.hydrogenaud.io/index.php?title=Tag_Mapping
https://kodi.wiki/view/Music_tagging#albumartists
=> New tags: Copyright, ISRC, Artists, AlbumArtists, URL

mediafile.py, test/test_mediafile.py
=> Convert mb_artistid and mb_albumartistid to lists

docs/index.rst, mediafile.py, test/test_mediafile.py, test/test_mediafile_edge.py
and simple and useful `MediaFile.as_dict()` function
Resolves #35
=> File-like objects support

mediafile.py
sum doesn't have any keyword arguments before python 3.8
fixes #53
probably should be tagged with 0.8.1 version to fix bug ;)
=> Fix python <=3.7 compatibility

docs/index.rst, mediafile.py, test/test_mediafile.py
Add support for:
* `albumtypes`
Parse secondary album types, like https://github.com/beetbox/beets/issues/2200 but from the file tags directly.
* `catalognums`
Releases with multiple CDs sometimes have multiple catalog numbers (for example [this release](https://musicbrainz.org/release/0af3dcfd-51b0-4cb0-87c0-cfa16a70ae71)).
* `languages`
A work on MusicBrainz can have multiple languages, and by using `Use track relationships` in Picard they get written to the files.
Until now, the values could be retrieved with a separator for ID3v2.3 tags, but not for Vorbis tags:
```python
>>> f = MediaFile('test.mp3')
>>> f.albumtype
'album/audio drama'
>>> f = MediaFile('test.flac')
>>> f.albumtype
'album'
```
With this PR:
```python
>>> f.albumtypes
['album', 'audio drama']
>>> f.albumtype
'album' …
```
=> Add new list fields set by MusicBrainz Picard

docs/index.rst, mediafile.py
Eg mp3tag was using DISCOGS_CATALOG a couple of years ago and is using CATALOGID, which my current tests using a trial version of mp3tag for macOS revealed.
This feature enables beets make use of these potentially available on-disk fields when importing and having `musicbrainz.extra_fields: ['catalognum']` set.
=> Support reading differently named catalog number file tags

docs/index.rst, mediafile.py
Some fight about tag naming in Picard is still having place: https://tickets.metabrainz.org/browse/PICARD-700
Meanwhile different software using this tag uses other variants for it.
e.g. Kodi can read `ALBUMARTISTS` and `ALBUM ARTISTS` while `jaudiotagger` is tagging files using `ALBUM_ARTISTS` tag.
=> More tag variants for `albumartists`

.github/workflows/build.yml, docs/index.rst, pyproject.toml, test/test_mediafile.py, tox.ini
Mutagen recently updated its policy for calculating bitrates for WAV files in https://github.com/quodlibet/mutagen/pull/566. So we now match the new/better output, and we require the version of Mutagen that produces this output.
As an added bonus, this does a little housecleaning on our Tox and GitHub Actions configuration.
=> Fix #65 (update some tests and dependencies)

.gitignore, mediafile.py, test/test_mediafile.py
=> list fields will now return `None` if the tag does not exist

docs/index.rst, mediafile.py, test/test_mediafile.py
As title, for the PR: https://github.com/beetbox/beets/pull/4743
On Ubuntu, I'm hitting a pre-existing test failure on WAVETest.test_read_audio_properties when reading the bitrate tag: `88200 != 705600`
=> multi-tags for artists + albumartists sort and credits

mediafile.py
The former is used by Plex Media Server to discern the original release date. Fixes #70
This behavior also matches other popular tagging libraries, such as https://github.com/Borewit/music-metadata
See referenced issue for examples
=> Set new ORIGINALDATE tag for m4a files in addition to existing "ORIGINAL YEAR" tag. 

mediafile.py, pyproject.toml, setup.cfg, test/__init__.py, test/_common.py, test/test_mediafile.py, test/test_mediafile_edge.py
Hi,
This is a little cleanup as requested on issue 68.
Greetings,
Closes: #68
=> remove usage of six & __future__

mediafile.py
... for an exact type match, use is or is not.
https://docs.astral.sh/ruff/rules/type-comparison/#type-comparison-e721
=> Fix linting issue E721: type-comparison
